# Status of the xCluster DR configuration #######################################

configuration:
  "Initializing": "xcluster DR objects in YBA have been created, and the configuration is pending changes at each universe's database level"
  "Replicating": "xCluster DR replication has been established between source and target"
  "Switchover": "the xCluster DR replication stream is in the process of switching over"
  "Failover in Progress": "the xCluster DR replication stream is in the process of failing over"
  "Halted": "xCluster DR replication was halted during failover because data is not in sync between source and target"
  "Error": "an error was experienced during replication (re)configuration"

# Status of the xCluster DR replication stream ##################################

replication:
  "Initialized": "the xCluster DR configuration has been applied, but replication is not yet running"
  "Running": "the configured xCluster DR replication is running (but may be paused)"
  "Updating": "the xCluster DR configuration is being changed for this stream"
  "DeletedUniverse": "either the source or the target has been force-deleted"
  "DeletionFailed": "removing the xCluster DR replication config has failed"
  "Failed": "an error was experienced during xCluster DR replication (re)configuration"

# Status of the source side of the xCluster DR replication stream ##############

source:
  "Unconfigured for DR": "this universe is not part of an xCluster DR configuration"
  "Ready to replicate": "checkpoints have been established on the source tables"
  "Waiting for DR": "backup of the source is completed; waiting for restore and setup to complete on the target"
  "Replicating data": "source is sending data to target without issue"
  "Preparing for switchover": "source is waiting for all remaining changes to be replicated to target"
  "Universe marked as DR failed": "a recovery is required to restore the DR replication, probably after failover"

# Status of the target side of the replication stream ###########################

target:
  "Unconfigured for DR": "this universe is not part of an xCluster DR configuration"
  "Bootstrapping": "a full copy (backup and restore) is being done from the source on the target"
  "Receiving data, Ready for reads": "target is receiving data from source without issue"
  "Switching to DR primary": "during a failover, the xCluster DR configuration is changing to make this the source"
  "Universe marked as DR failed": "a recovery is required to restore the DR replication, probably after failover"

# Is xCluster DR replication paused? ############################################

paused:
  True: "xCluster DR replication has been paused, and no data is being replicated between source and target"
  False: "xCluster DR replication is not paused (has never been paused or was resumed after being paused), and so data is being replicated between source and target"
